### ISSUE TITLE
readonly does not work

### ISSUE THREAD

**Issue by freeranger** [vlad-ignatov/react-numeric-input#15]
Hi,

The readonly propery doesn't seem to do work.
On the examples page, I can change the value using the up and down buttons, though I cannot enter a value in the text field directly.

For the control to be "read only" I would expect not to be able to change the value with the up/down buttons either

**Comment by vlad-ignatov** [comment]
Well, that is by design. It is a common use-case to set `readonly` just to disallow manual typing into the input. This way the author forces the users to use the up/down buttons (or keys) and guarantees that only valid entries will be entered.

If you also want the buttons disabled then use `disabled` instead (although that will exclude the value from submitted forms).

The truth is that what you are expecting makes sense too and I am not sure how to proceed.
Perhaps in the next version another prop can be added to hint how to handle buttons in read-only mode?

I will keep this issue open for now and I hope to get more opinions before I decide how to proceed.

**Comment by freeranger** [comment]
Personally I have only ever seen readonly to mean the whole control is read only. 
Perhaps what you actually need is a disableTyping prop which does what readonly does now and readonly does indeed make the whole control read only?  Semantically that makes more sense IMO

**Comment by vlad-ignatov** [comment]
As of version 2.2.2 this was updated and `readOnly` behaves the way you were expecting.

**Comment by virtualkitchenco** [comment]
Original readonly is a good feature. How to disallow manual typing without disabling +/- now?

**Comment by aalba-finsol** [comment]
Facing the same issue, I want only to disable manual typing, wich property can we use?

Edit:
Ended up migrating to version 2.2.1
