### ISSUE TITLE
Does this library supprt dynamic precision for floating point numbers and negative numbers

### ISSUE THREAD

**Issue by akiran** [vlad-ignatov/react-numeric-input#21]
Thanks for this library.
I am trying to this library and has few questions about it
1) Is it possible to have dynamic precision i.e can we have any number of digits after dot or can we remove dot if field can have both integer and floating point numbers
2) Does this support negative numbers ?

**Comment by vlad-ignatov** [comment]
Yes, it does support negative numbers. I fact, if you don't want them you will have to set the `min` prop to 0 (or bigger).

As for the dynamic precision (or simply "missing precision") that is not on by default. The reason is that nobody would want to use actual floats due to their rounding issues. For example in JS `0.2 + 0.4 = 0.6000000000000001`. Imagine that you have an input like this:
```js
<NumericInput value={0} step={0.2}/>
```
Then if you click the up button once it will display `0.2`.
If you click the up button five times it will display `1`.
If you click the up button three times it will display `0.6000000000000001`!

To fix these issues and support what you are asking this widget can be configured like so:
```js
<NumericInput format={ parseFloat } precision={ 10 }/>
```
