### ISSUE TITLE
Can't override input box border color or size

### ISSUE THREAD

**Issue by mattnedrich** [vlad-ignatov/react-numeric-input#28]
It doesn't appear that you can override the input box's border size or color. Is that true?

**Comment by dcefram** [comment]
You can, but it's not under "input". Upon checking the [source code](https://github.com/vlad-ignatov/react-numeric-input/blob/master/src/NumericInput.jsx#L241), I found out that I should override `input:not(.form-control)` prop.

So it'll be:

```jsx
<NumericInput 
  style={{ 
    'input:not(.form-control)': { 
      border: '1px solid #000' 
    }
  }}
/>
```

**Comment by vlad-ignatov** [comment]
Yes, you can customize everything. Also take a look at the demo page examples: http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.5/index.html.

I guess you were trying to supply an inline styles while the component expects a CSS-like structure because this way you can customize all the elements nested within it. There are 3 ways to have custom styles:
- You can provide a style prop for each component
- You can modify the static `NumericInput.style` property which will change the default style for all the components on the page.
- You can set the `style` prop to `false`. This will remove all the inline styles and then you can write your own CSS using the fact the the component is `.react-numeric-input`.
