### ISSUE TITLE
target not passed through events

### ISSUE THREAD

**Issue by MihaMarkic** [vlad-ignatov/react-numeric-input#34]
I can't handle multiple numeric inputs through a single function because only values are passed but not something to identify the source, such as target.
Or am I missing something?

**Comment by gazofnaz** [comment]
[The comment here](https://github.com/vlad-ignatov/react-numeric-input/issues/5#issuecomment-179205866) suggests using a separate onChange function for every `NumericInput`... not ideal when incrementing multiple counters and every onChange event is the same apart from the input target.

**Comment by vlad-ignatov** [comment]
There are multiple reasons for changing the value. Some of them are artificial and don't have corresponding change event. That is why the onChange handler did not receive an event. 

However, your concern is valid and since 2.1.0 the input element is available as additional argument in the onChange handlers. I hope that works for you.

**Comment by vlad-ignatov** [comment]
Closing this issue because it is too old. Feel free to reopen if needed.
