### ISSUE TITLE
Does not change the value at all

### ISSUE THREAD

**Issue by junibrosas** [vlad-ignatov/react-numeric-input#51]
The latest version of the library (2.0.9) has some issue regarding the value of the input does not change at all.

To replicate, enter 215.62 value, and then select all (ctrl+a,cmd+a) then hit 7 or whatever number. It should change like the previous version (2.0.7). Is this intentional?

**Comment by vlad-ignatov** [comment]
Thank you for reporting this. It is not intentional. It appears to be a side effect of https://github.com/vlad-ignatov/react-numeric-input/pull/36. I have made a fix and if everything is OK I intend to release it with the next version in a few days. You may want to use the github version until then.

**Comment by vlad-ignatov** [comment]
Just published the new version (2.1.0) on npm. I wonder if you can confirm that it works for you?

**Comment by junibrosas** [comment]
@vlad-ignatov Hi, yes, I totally worked for me now. Good to hear about the update. Thanks.

**Comment by vlad-ignatov** [comment]
Thank you.
