### ISSUE TITLE
manual edit in case on floating point number leads to one digit value

### ISSUE THREAD

**Issue by sanjeev2838** [vlad-ignatov/react-numeric-input#9]

**Comment by vlad-ignatov** [comment]
Could you provide an example with the props that you are passing?

**Comment by sanjeev2838** [comment]
Hi vlad,

Sorry for late reply.
If you try to type any floating point number having two digits like ( 50.3)
most of the cases it will record 5.0 in the input.

let me know if you need more information.

Thanks

**Comment by tjmcewan** [comment]
@vlad-ignatov using the float enabled component on your [example page](http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.4/index.html) (`<NumericInput step={0.1} precision={2} value={50.3}/>`), if you type the keys: `5 . 5`, then the field will not show 5.5, but rather 5.01.

**Comment by vlad-ignatov** [comment]
This was related to issues like [facebook/react#955](https://github.com/facebook/react/issues/955). The latest version (2.0.5) should work much better because it is persisting the selection by it's own. You can try it on the updated demo page [here](http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.5/index.html)
